### ISSUE TITLE
Не получается клонировать репозиторий

### ISSUE THREAD

**Issue by aardalin** [Heron345/infra-wordpress#1]
Решил развернуть на своем существующем сервере этот контейнер, пройти по мануалу.

1. там где предлагается создать судо пользователя имеет смысл прописать логику только через создание судо пользователя, дополнить командой переключения на этого пользователя и уже дополнить команды update && upgrade с sudo;

2. При клонировании просит в терминале авторизоваться в гитхаб, при введении всех данных пишет что по паролю авторизация давно не работает. Как клонировать проект по человечески, если исключить версию "скачать себе архив и заливать с локалки на прод"?

**Comment by kran0** [comment]
https://github.com/Heron345/infra-wordpress.git is now public repo, you can clone it without authorization.

**Comment by kran0** [comment]
Ready to close, please verify
